//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Stu_Rollno { get; set; }
        public string Stu_Name { get; set; }
        public string Stu_city { get; set; }
        public string Stu_state { get; set; }
        public string Stu_country { get; set; }
    }
}
